server:
  port: 80
spring:
  application:
    name: TTMS
  datasource:
    url: jdbc:mysql://localhost:3306/student?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: lhf521
    driver-class-name: com.mysql.jdbc.Driver

